apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 30s
  url: https://github.com/buzzfrog/podinfo
  ref:
    branch: master