apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: notification-sink-provider
  namespace: default
spec:
  type: generic
  address: http://notification-sink-service.default/event
